### ISSUE TITLE
Footer colides with wiki content

### ISSUE THREAD

**Issue by jstkdng** [techandbeers/moneromine-wiki#3]
Just what the title says.
![image](https://user-images.githubusercontent.com/52050345/111079517-50de3e80-84c8-11eb-947f-87efb92fb843.png)

**Comment by techandbeers** [comment]
@jstkdng Thanks for reporting, will get this patched up soon!

**Comment by techandbeers** [comment]
@jstkdng This should now be resolved with the last commit.
